### ISSUE TITLE
"org.apache.cordova.background-download" might be not access.

### ISSUE THREAD

**Issue by baixiaoshengofficial** [jellyfin-archive/emby-ios#1]
Installing "org.apache.cordova.background-download" for ios
Failed to install 'org.apache.cordova.background-download': CordovaError: Failed to fetch plugin org.apache.cordova.file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/org.apache.cordova.file - Not found
npm ERR! 404
npm ERR! 404  'org.apache.cordova.file@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chenqinfeng/.npm/_logs/2019-04-15T09_28_17_902Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:146:43
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Failed to fetch plugin org.apache.cordova.file via registry.

**Comment by anthonylavado** [comment]
@jokerknight Hi there :wave: 
This project is actually unusable in it's current state, and we will be archiving it. We are working on newer client applications for the future, but there is no significant progress at this time.

Right now, new client applications are planned to be cross-platform in the https://github.com/jellyfin/jellyfin-react-client repository. In case that ever changes, please feel free to look through our repository list.

https://github.com/jellyfin

Thanks!
